# SPDX-License-Identifier: GPL-3.0-or-later
"""Collect exact license/notice files for dependencies installed on this PC.

This is a redistribution helper. It does not replace reading the authoritative
upstream license terms. Output is generated under build/ and is not committed.
"""
from __future__ import annotations

import importlib.metadata as md
import json
import os
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "build" / "installed-licenses"
VCPKG = ROOT / ".deps" / "vcpkg" / "installed" / "x64-windows"

if OUT.exists():
    shutil.rmtree(OUT)
(OUT / "vcpkg").mkdir(parents=True, exist_ok=True)
(OUT / "python").mkdir(parents=True, exist_ok=True)

# vcpkg puts each port's authoritative copyright/license record here.
manifest = []
share = VCPKG / "share"
if share.exists():
    for port in sorted(p for p in share.iterdir() if p.is_dir()):
        copied=[]
        for name in ("copyright", "LICENSE", "LICENSE.txt", "NOTICE", "NOTICE.txt", "COPYING", "COPYING.txt"):
            src=port/name
            if src.is_file():
                dst=OUT/"vcpkg"/f"{port.name}--{name.replace('/', '_')}"
                shutil.copy2(src,dst)
                copied.append(dst.name)
        if copied:
            manifest.append({"kind":"vcpkg","name":port.name,"files":copied})

# Python wheels usually place license files inside *.dist-info/licenses or the
# dist-info directory. Copy what the installed distribution actually shipped.
for dist in sorted(md.distributions(), key=lambda d: (d.metadata.get('Name') or '').lower()):
    name=dist.metadata.get('Name') or 'unknown'
    version=dist.version
    files=[]
    for f in dist.files or []:
        base=Path(str(f)).name.lower()
        full=str(f).replace('\\','/').lower()
        if ('license' in base or 'copying' in base or 'notice' in base or '/licenses/' in full):
            try:
                src=Path(dist.locate_file(f))
                if src.is_file():
                    safe=re.sub(r'[^A-Za-z0-9_.-]+','_',str(f))
                    dst=OUT/'python'/f"{name}-{version}--{safe}"
                    dst.parent.mkdir(parents=True,exist_ok=True)
                    shutil.copy2(src,dst)
                    files.append(dst.name)
            except Exception:
                pass
    manifest.append({
        "kind":"python", "name":name, "version":version,
        "metadata_license":dist.metadata.get('License'), "files":files,
    })

(OUT/'manifest.json').write_text(json.dumps(manifest,indent=2,sort_keys=True),encoding='utf-8')
(OUT/'README.txt').write_text(
    "Generated by WTiVo scripts/collect_dependency_licenses.py.\n"
    "Keep this directory with any redistribution that bundles the corresponding installed dependencies.\n"
    "The upstream license texts and package metadata are authoritative.\n",
    encoding='utf-8')
print(f"[WTiVo] Installed dependency licenses collected in: {OUT}")
